/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#F8FAFC',
        'surface-dim': '#E2E8F0',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F1F5F9',
        'surface-container': '#ECEEF0',
        'surface-container-high': '#E6E8EA',
        'surface-container-highest': '#E0E3E5',
        'on-surface': '#191C1E',
        'on-surface-variant': '#41484C',
        'inverse-surface': '#2D3133',
        'inverse-on-surface': '#EFF1F3',
        outline: '#71787D',
        'outline-variant': '#CBD5E1',
        primary: '#104358',
        'primary-container': '#2D5A70',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#A4D0EA',
        secondary: '#775A19',
        'secondary-container': '#FED488',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#785A1A',
        error: '#DC2626',
        'on-error': '#FFFFFF',
        'error-container': '#FFDAD6',
        background: '#F8FAFC',
        'on-background': '#191C1E',
        'deep-teal': '#2D5A70',
        'champagne-gold': '#C5A059',
        'slate-muted': '#475569',
        'success-emerald': '#10B981',
        'error-rose': '#E11D48',
        'warning-amber': '#CA8A04',
        'sidebar-bg': '#104358',
        'sidebar-active': '#1E3E4E',
      },
      fontFamily: {
        heading: ['"Plus Jakarta Sans"', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '260px',
        'sidebar-width-collapsed': '80px',
        'gutter-md': '24px',
        'margin-page': '32px',
        'margin-page-mobile': '16px',
        'container-max': '1440px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
      },
    },
  },
  plugins: [],
}
